name: Gerar APK Combio V34

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Extrair projeto V34
        run: unzip -o Combio_V34_APK_Projeto_CORRECAO_CODIGO_BARRAS.zip -d apk-project

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.9'

      - name: Criar Gradle Wrapper
        working-directory: apk-project/combio_apk_v32
        run: gradle wrapper --gradle-version 8.9

      - name: Gerar APK
        working-directory: apk-project/combio_apk_v32
        run: ./gradlew assembleDebug

      - name: Disponibilizar APK
        uses: actions/upload-artifact@v4
        with:
          name: Combio-V34-APK
          path: apk-project/combio_apk_v32/app/build/outputs/apk/debug/*.apk
